version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - cd backend
      - python -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
  pre_build:
    commands:
      - python manage.py migrate
      - python manage.py collectstatic --noinput
  build:
    commands:
      - echo "Django build complete"
artifacts:
  files:
    - '**/*'
